language: python
python:
  - "3.7"
env:
  - CODECOV_TOKEN=194cff37-3a7a-4186-aaff-8f4d82fc9fb1
before_install:
  - sudo apt-get -y install default-jdk maven
addons:
  apt:
    update: true
install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - mvn --version
  - coverage erase
  - coverage run -m pytest --cov-report term tests integration
  - coverage report --fail-under 80
after_success:
  - codecov
